version: '2'

services:
  db:
    image:  mariadb
    ports:
    - 13306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    volumes:
    - $PWD/data/mariadb:/var/lib/mysql
    - $PWD/etc/mariadb/my.cnf:/etc/mysql/my.cnf
    command: 'mysqld --innodb-flush-method=fsync'